$~$ $Vraj$ $Patel$
# Autograd

Autograd is a core component of PyTorch taht provides automatic differentiaion for tensor operations.

It enables gradient computation, which is essential for training machine learning models using optimization algorithms like gradient descent

In [41]:
import torch

In [42]:
x = torch.tensor(3.0, requires_grad=True) # scaler tensor for now

In [43]:
y = x**2

In [44]:
y

tensor(9., grad_fn=<PowBackward0>)

In [45]:
y.backward()

In [46]:
x.grad

tensor(6.)

In [47]:
# another example
x = torch.tensor(3.0, requires_grad=True)

In [48]:
y = x ** 2

In [49]:
z = torch.sin(y)

In [50]:
print(x)
print(y)
print(z)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)
tensor(0.4121, grad_fn=<SinBackward0>)


In [51]:
z.backward()

In [52]:
x.grad

tensor(-5.4668)

In [53]:
x = torch.tensor(3.4)
y = torch.tensor(0.0)

In [54]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [55]:
w

tensor(1., requires_grad=True)

In [56]:
b

tensor(0., requires_grad=True)

In [57]:
z = w*x + b
z

tensor(3.4000, grad_fn=<AddBackward0>)

In [58]:
y_pred = torch.sigmoid(z)

In [59]:
y_pred

tensor(0.9677, grad_fn=<SigmoidBackward0>)

In [60]:
import tensorflow as tf
loss = tf.keras.losses.BinaryCrossentropy(y_pred,y)

In [61]:
# vector input tensors
x = torch.tensor([2.0,3.0,4.0], requires_grad=True)

In [62]:
x

tensor([2., 3., 4.], requires_grad=True)

In [63]:
y = (x**2).mean()

In [64]:
y

tensor(9.6667, grad_fn=<MeanBackward0>)

In [65]:
y.backward()

In [66]:
x.grad

tensor([1.3333, 2.0000, 2.6667])

# Clearing Gradients

When we call gradients multiple times, the gradients starts accumulating, which is not a good thing. We have to clear it


` We clear gradients every epochs`

In [67]:
x.grad

tensor([1.3333, 2.0000, 2.6667])

In [68]:
x.grad.zero_()

tensor([0., 0., 0.])

# Disabling Graident Tracking

1. requires_grad_(False)
2. detach()
3. torch.no_grad()

In [69]:
x.requires_grad_(False)

tensor([2., 3., 4.])