# Intro on pytorch

# $Vraj Patel$

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


# Tensors

In [2]:
# empty tensor
torch.empty(2,3)

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31],
        [7.2148e+22, 1.5766e-19, 1.0256e-08]])

In [3]:
# checking the type
type(torch.empty(2,3))

torch.Tensor

In [5]:
# using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.1974, 0.3989, 0.1928],
        [0.2611, 0.1844, 0.0459]])

In [9]:
# using of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# using tensor
torch.tensor([[1,2,3], [9,8,7]])

tensor([[1, 2, 3],
        [9, 8, 7]])

In [12]:
# other ways
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [13]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [14]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# Tensor Shapes

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[197568495720, 433791697012, 493921239150],
        [489626271855, 390842023976, 210453397595]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [28]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

# Tensor Datatype

In [24]:
x.dtype

torch.int64

In [25]:
# pre assigning the data type
torch.tensor([[1.0,2.0,3.0], [4.0,5.0,6.0]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [26]:
torch.tensor([[1.0,2.0,3.0], [4.0,5.0,6.0]], dtype=torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [27]:
# using a to functin
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#Mathematical Operations


In [29]:
# scalar operation
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [30]:
x + 2

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])

In [31]:
x * 0.1

tensor([[0.0224, 0.0302],
        [0.0178, 0.0824]])

In [32]:
x / 0.1

tensor([[2.2389, 3.0235],
        [1.7842, 8.2384]])

In [33]:
x % 2

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [35]:
# Element wise operation
x = torch.rand(2,3)
y = torch.rand(2,3)
print(x)
print(y)

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])
tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])


In [36]:
x + y

tensor([[0.5332, 0.2568, 1.6012],
        [1.0494, 0.4811, 1.4163]])

In [37]:
x - y

tensor([[-0.4994,  0.1850,  0.3059],
        [ 0.3634, -0.1554,  0.3641]])

In [38]:
x * y

tensor([[0.0087, 0.0079, 0.6175],
        [0.2423, 0.0518, 0.4683]])

In [39]:
x / y

tensor([[0.0327, 6.1557, 1.4723],
        [2.0593, 0.5118, 1.6921]])

In [40]:
x % y

tensor([[0.0169, 0.0056, 0.3059],
        [0.0204, 0.1629, 0.3641]])

In [41]:
x * 3

tensor([[0.0507, 0.6627, 2.8606],
        [2.1192, 0.4886, 2.6706]])

In [42]:
torch.neg(x)

tensor([[-0.0169, -0.2209, -0.9535],
        [-0.7064, -0.1629, -0.8902]])

In [43]:
torch.round(y)

tensor([[1., 0., 1.],
        [0., 0., 1.]])

In [45]:
torch.ceil(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [46]:
torch.floor(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [48]:
# using clamp we can decide a range of all the numbers
torch.clamp(y, min=2, max = 5)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [49]:
# Reduction operation
e = torch.randint(size=(2,3), low=3, high = 10)

In [50]:
e

tensor([[9, 6, 7],
        [4, 7, 5]])

In [51]:
torch.sum(e)

tensor(38)

In [52]:
torch.sum(e, dim=0)

tensor([13, 13, 12])

In [53]:
torch.sum(e,dim=1)

tensor([22, 16])

In [55]:
torch.mean(e.to(torch.float32))

tensor(6.3333)

In [56]:
torch.median(e.to(torch.float32))

tensor(6.)

In [57]:
torch.max(e.to(torch.float32))

tensor(9.)

In [58]:
torch.min(e.to(torch.float32))

tensor(4.)

In [60]:
torch.std(e.to(torch.float32))

tensor(1.7512)

In [61]:
torch.var(e.to(torch.float32))

tensor(3.0667)

In [62]:
torch.argmax(e.to(torch.float32)) # returns the position of the max item

tensor(0)

In [64]:
torch.argmin(e.to(torch.float32)) # returns the position of the min item

tensor(3)

In [69]:
# Matrix Operations
a = torch.randint(size=(2,3), low=0, high = 32)
b = torch.randint(size=(3,2), low=0, high = 32)

In [70]:
print(a)

tensor([[17, 30, 16],
        [15,  7, 13]])


In [71]:
print(b)

tensor([[ 6, 12],
        [18,  0],
        [24,  2]])


In [72]:
torch.matmul(a,b)

tensor([[1026,  236],
        [ 528,  206]])

In [73]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])
torch.dot(v1,v2)

tensor(11)

In [74]:
torch.transpose(a,0,1)

tensor([[17, 15],
        [30,  7],
        [16, 13]])

In [75]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[7., 2., 3.],
        [8., 5., 6.],
        [2., 9., 5.]])

In [79]:
# determinant
torch.det(h)

tensor(-73.)

In [80]:
torch.inverse(h)

tensor([[ 0.3973, -0.2329,  0.0411],
        [ 0.3836, -0.3973,  0.2466],
        [-0.8493,  0.8082, -0.2603]])

In [81]:
h

tensor([[7., 2., 3.],
        [8., 5., 6.],
        [2., 9., 5.]])

# few sepecial func


In [84]:
a = torch.randint(size=(2,3), low=0, high = 10)

In [85]:
a

tensor([[0, 4, 2],
        [7, 1, 1]])

In [86]:
torch.log(a)

tensor([[  -inf, 1.3863, 0.6931],
        [1.9459, 0.0000, 0.0000]])

In [87]:
torch.exp(a)

tensor([[1.0000e+00, 5.4598e+01, 7.3891e+00],
        [1.0966e+03, 2.7183e+00, 2.7183e+00]])

In [88]:
torch.sqrt(a)

tensor([[0.0000, 2.0000, 1.4142],
        [2.6458, 1.0000, 1.0000]])

In [89]:
torch.sigmoid(a)

tensor([[0.5000, 0.9820, 0.8808],
        [0.9991, 0.7311, 0.7311]])

In [94]:
torch.softmax(a.to(torch.float32), dim=0)

tensor([[9.1105e-04, 9.5257e-01, 7.3106e-01],
        [9.9909e-01, 4.7426e-02, 2.6894e-01]])

In [96]:
torch.relu(a.to(torch.float32))

tensor([[0., 4., 2.],
        [7., 1., 1.]])

# Inplace Operations

In [98]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])
tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])


In [105]:
m.add_(n)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [106]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [107]:
n

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [109]:
torch.relu(m) # this would not have dont changes to the tensor itself. it will be a copy

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [112]:
# in order to do permanent changes by just adding a '_' underscore infront of the paranthese while calling a function
torch.relu_(m)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [113]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

# Tensor operations on GPU

In [115]:
torch.cuda.is_available()

True

In [116]:
device = torch.device('cuda')

In [117]:
# creating a new tensor on the GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [118]:
# moving existing the tensors from CPU to GPU
b = a.to(device)

tensor([[0, 4, 2],
        [7, 1, 1]])

# Reshaping tensors

In [119]:
a = torch.ones(4,4)

In [120]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [122]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [123]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [124]:
b = torch.rand(2,3,4)
b

tensor([[[0.4175, 0.0340, 0.9157, 0.3079],
         [0.6269, 0.8277, 0.6594, 0.0887],
         [0.4890, 0.5887, 0.7340, 0.8497]],

        [[0.9112, 0.4847, 0.9436, 0.3904],
         [0.2499, 0.3206, 0.9753, 0.7582],
         [0.6688, 0.2651, 0.2336, 0.5057]]])

In [125]:
# permute
b.permute(2,0,1) # means in tensor b, the the 0th position will is 2 and here it will be at 2 same with others

tensor([[[0.4175, 0.6269, 0.4890],
         [0.9112, 0.2499, 0.6688]],

        [[0.0340, 0.8277, 0.5887],
         [0.4847, 0.3206, 0.2651]],

        [[0.9157, 0.6594, 0.7340],
         [0.9436, 0.9753, 0.2336]],

        [[0.3079, 0.0887, 0.8497],
         [0.3904, 0.7582, 0.5057]]])

In [133]:
# unsqueeze
c = torch.rand(226,226,3)

In [129]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [130]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

# Numpy and Pytorch

In [135]:
import numpy as np

In [136]:
a = torch.tensor([1,2,3])

In [137]:
b = a.numpy()

In [138]:
b

array([1, 2, 3])

In [139]:
a

tensor([1, 2, 3])

In [141]:
g = np.array([1,2,3])

In [142]:
torch.from_numpy(g)

tensor([1, 2, 3])